/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlbumDataView: typeof import('./src/components/AlbumDataView/index.vue')['default']
    AnimatedDiv: typeof import('./src/components/AnimatedDiv.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader/index.vue')['default']
    AppSideBar: typeof import('./src/components/AppSideBar/index.vue')['default']
    BottomLoadingState: typeof import('./src/components/BottomLoadingState.vue')['default']
    Button: typeof import('primevue/button')['default']
    Chip: typeof import('primevue/chip')['default']
    CommonMusicSheet: typeof import('./src/components/CommonMusicSheet.vue')['default']
    CustomDataTable: typeof import('./src/components/CustomDataTable.vue')['default']
    Empty: typeof import('./src/components/Empty.vue')['default']
    FixedDataTable: typeof import('./src/components/FixedDataTable.vue')['default']
    Header: typeof import('./src/components/MusicSheetView/Header.vue')['default']
    IconField: typeof import('primevue/iconfield')['default']
    ImportMusicSheetModal: typeof import('./src/components/ImportMusicSheetModal.vue')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    LoadingOrEmpty: typeof import('./src/components/LoadingOrEmpty.vue')['default']
    LyricView: typeof import('./src/components/LyricView.vue')['default']
    MainContent: typeof import('./src/components/MainContent/index.vue')['default']
    MusicDownloaded: typeof import('./src/components/MusicDownloaded.vue')['default']
    MusicFavorite: typeof import('./src/components/MusicFavorite.vue')['default']
    MusicList: typeof import('./src/components/MusicList.vue')['default']
    MusicSheetCard: typeof import('./src/components/MusicSheetDataView/MusicSheetCard.vue')['default']
    MusicSheetDataView: typeof import('./src/components/MusicSheetDataView/index.vue')['default']
    MusicSheetModal: typeof import('./src/components/AppSideBar/MusicSheetModal.vue')['default']
    MusicSheetSelectionDialog: typeof import('./src/components/MusicSheetSelectionDialog.vue')['default']
    MusicSheetView: typeof import('./src/components/MusicSheetView/index.vue')['default']
    NowPlaying: typeof import('./src/components/NowPlaying/index.vue')['default']
    PlaylistDrawer: typeof import('./src/components/PlaylistDrawer.vue')['default']
    PluginListModal: typeof import('./src/components/PluginListModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarItem: typeof import('./src/components/AppSideBar/SidebarItem.vue')['default']
    SvgAsset: typeof import('./src/components/SvgAsset.vue')['default']
    Tab: typeof import('primevue/tab')['default']
    TabList: typeof import('primevue/tablist')['default']
    Tabs: typeof import('primevue/tabs')['default']
    Tag: typeof import('./src/components/Tag.vue')['default']
  }
}
