/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/AppHeader/index.vue')['default']
    AppSideBar: typeof import('./src/components/AppSideBar/index.vue')['default']
    Button: typeof import('primevue/button')['default']
    IconField: typeof import('primevue/iconfield')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    MainContent: typeof import('./src/components/MainContent/index.vue')['default']
    Menu: typeof import('primevue/menu')['default']
    NowPlaying: typeof import('./src/components/NowPlaying/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('primevue/sidebar')['default']
    SideBar: typeof import('./src/components/SideBar/index.vue')['default']
    SidebarItem: typeof import('./src/components/AppSideBar/SidebarItem.vue')['default']
    SvgAsset: typeof import('./src/components/SvgAsset.vue')['default']
  }
}
