/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/AppHeader/index.vue')['default']
    AppSideBar: typeof import('./src/components/AppSideBar/index.vue')['default']
    BottomLoadingState: typeof import('./src/components/BottomLoadingState.vue')['default']
    Button: typeof import('primevue/button')['default']
    EmptyView: typeof import('./src/components/EmptyView.vue')['default']
    IconField: typeof import('primevue/iconfield')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    LoadingOrEmpty: typeof import('./src/components/LoadingOrEmpty.vue')['default']
    MainContent: typeof import('./src/components/MainContent/index.vue')['default']
    NowPlaying: typeof import('./src/components/NowPlaying/index.vue')['default']
    PlaylistDrawer: typeof import('./src/components/PlaylistDrawer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarItem: typeof import('./src/components/AppSideBar/SidebarItem.vue')['default']
    SvgAsset: typeof import('./src/components/SvgAsset.vue')['default']
    SwitchCase: typeof import('./src/components/SwitchCase.vue')['default']
    TabMenu: typeof import('primevue/tabmenu')['default']
  }
}
